### PR TITLE
Experiment - webpack dll

### PR DESCRIPTION
**Pull request by nodar-chkuaselidze**
This is the webpack DLLPlugin experiment.

Try and experiment with it, see if it gives performance boost and how can we use this for development environment.

* Added script - `npm run build:dll` - which is necessary in development mode (to run once, and if you update the plugins listed in webpack.dll.config.js.
* Fixes minor problem - Uglify was used in dev mode.

### CODE REVIEW

**Comment by bucko13** [comment]
Do you think it makes sense to have a webpack directory? I could see us also splitting out configs for prod and dev too

**Comment by tynes** [comment]
I think that it does make sense to have a webpack directory.
Prod webpack would be for an actual user while the dev webpack would be for a developer correct?

**Comment by Thann** [comment]
I'm not a huge fan of "splitting up the webpack config", because I think the configs should be fairly simple and share most of their config. I think a better solution would be to add a "--env.dll" param to webpack and inject these changes into the config.

**Comment by nodar-chkuaselidze** [comment]
Having them in one file won't change much, it will still be two separate webpack configs - Just in one file. In the future if we have multiple setups or experiment more with new webpack plugins, we will need to have other files as well..

If after some time we have good solutions (we don't wait for 3 seconds or more in dev env), we can merge them back in one file. This part needs more exploration, that's why I tagged this as experiment.

@bucko13 @tynes Did you try to use this ?

**Comment by bucko13** [comment]
We talked a bit about here, and I agree that for now it's nice to have them separated out. There's a chance we will end up having more different configurations too, which is why I suggested maybe having a dedicated webpack folder. Haven't had a chance to test out yet, but will try it soon.

**Comment by bucko13** [comment]
Added with #83 Sorry it took so long!

**Pull request closed without merging**
